import "@/app/ui/global.css";
import { inter } from "./ui/fonts";
import RegisterSW from "./RegisterSW";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next PWA Dashboard App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: { icon: "/favicon.ico", apple: "/favicon.ico" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {/* <RegisterSW /> */}
        {children}
      </body>
    </html>
  );
}
